# Generated by Django 6.0.4 on 2026-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата запиту')),
                ('is_called', models.BooleanField(default=False, verbose_name='Передзвонили?')),
            ],
            options={
                'verbose_name': 'Зворотній дзвінок',
                'verbose_name_plural': 'Зворотні дзвінки',
                'ordering': ('-created',),
            },
        ),
    ]
